OENIK_PROG3_2020_2_WN1M1P/MyMoviesFF.Web/Models/Actor.cs
// <copyright file="Actor.cs" company="WN1M1P">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace MyMoviesFF.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;
    using MyMoviesFF.Data;

    /// <summary>
    /// Contains Actor's attributes, which will be used.
    /// </summary>
    public class Actor
    {
        /// <summary>
        /// Gets or sets the Actor's id.
        /// </summary>
        [Display(Name = "Actor Id")]
        [Required]
        public int ActorId { get; set; }

        /// <summary>
        /// Gets or sets the Actor's name.
        /// </summary>
        [Display(Name = "Actor Name")]
        [Required]
        public string ActorName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the Actor is a male(1) or a female(0).
        /// </summary>
        [Display(Name = "Actor's gender")]
        [Required]
        public bool Gender { get; set; }

        /// <summary>
        /// Gets or sets the Actor's age.
        /// </summary>
        [Display(Name = "Actor's age")]
        [Required]
        public int Age { get; set; }

        /// <summary>
        /// Gets or sets how movies has the actor's played.
        /// </summary>
        [Display(Name = "Movie Count")]
        public int MovieCount { get; set; }

        /// <summary>
        /// Gets or sets the Actor's movies, which is in the database.
        /// </summary>
        [Display(Name = "Movies")]
        public ICollection<MovieActor> MovieActors { get; set; }

        /// <summary>
        /// Gets or sets the Actor's country.
        /// </summary>
        [Display(Name = "Actor's country")]
        [Required]
        public string Country { get; set; }
    }
}

OENIK_PROG3_2020_2_WN1M1P/MyMoviesFF.Web/Controllers/ActorsController.cs
// <copyright file="ActorsController.cs" company="WN1M1P">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace MyMoviesFF.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using MyMoviesFF.Logic;
    using MyMoviesFF.Web.Models;

    /// <summary>
    /// Controls the Actor related features.
    /// </summary>
    public class ActorsController : Controller
    {
        private IActingLogic actingLogic;
        private IMapper mapper;
        private ActorListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="ActorsController"/> class.
        /// </summary>
        /// <param name="actingLogic">IActtingLogic implementation.</param>
        /// <param name="mapper">IMapper implementation.</param>
        public ActorsController(IActingLogic actingLogic, IMapper mapper)
        {
            this.actingLogic = actingLogic;
            this.mapper = mapper;
            this.vm = new ActorListViewModel();
            this.vm.EditedActor = new Actor();
            var actors = actingLogic?.GetAllActors();
            this.vm.ListOfActors = mapper?.Map<IList<MyMoviesFF.Data.Actor>, List<Actor>>(actors);
        }

        /// <summary>
        /// Shows the Index.
        /// </summary>
        /// <returns>Returns an IActionResult.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew"; // actorseditnek kell egy  editaction
            return this.View("ActorsIndex", this.vm);
        }

        /// <summary>
        /// Shows one Actor's details.
        /// </summary>
        /// <param name="id">Actor's id.</param>
        /// <returns>Returns an ActorsDetails IActionResult.</returns>
        public IActionResult Details(int id)
        {
            // GET: Actors/Details/5  //5=id
            return this.View("ActorsDetails", this.GetActorModel(id));
        }

        /// <summary>
        /// Removes one Actor.
        /// </summary>
        /// <param name="id">Actor's id.</param>
        /// <returns>Returns an EditResult IActionResult.</returns>
        public IActionResult Remove(int id)
        {
            // GET: Actors/Remove/5  //5=id
            this.TempData["editResult"] = "DELETE FAIL";
            if (this.actingLogic.RemoveActor(this.actingLogic.GetOneActor(id)))
            {
                this.TempData["editResult"] = "DELETE OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edits one Actor.
        /// </summary>
        /// <param name="id">Actor's id.</param>
        /// <returns>Returns an EditAction IActionResult.</returns>
        public IActionResult Edit(int id)
        {
            // GET: Actors/Edit/5  //5=id
            this.ViewData["editAction"] = "Edit"; // actorseditnek kell egy  editaction
            this.vm.EditedActor = this.GetActorModel(id);
            return this.View("ActorsIndex", this.vm);
        }

        /// <summary>
        /// Edits or Adds an Actor.
        /// </summary>
        /// <param name="actor">Actor entity.</param>
        /// <param name="editAction">Action string(AddNew or Edit).</param>
        /// <returns>Returns an EditAction IActionResult.</returns>
        [HttpPost]
        public IActionResult Edit(Actor actor, string editAction)
        {
            // Post: Actors/Edit + 1 actor + editAction
            if (this.ModelState.IsValid && actor != null)
            {
                this.TempData["editResult"] = "EDIT OK";
                if (editAction == "AddNew")
                {
                    this.actingLogic.InsertNewActor(actor.ActorName, actor.Gender, actor.Age, 0, actor.Country);
                }
                else
                {
                    if (!this.actingLogic.ChangeActor(actor.ActorId, actor.ActorName, actor.Gender, actor.Age, actor.Country))
                    {
                        this.TempData["editResult"] = "EDIT FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit"; // actorseditnek kell egy  editaction
                this.vm.EditedActor = actor;
                return this.View("ActorsIndex", this.vm);
            }
        }

        /// <summary>
        /// Converts MyMoviesFF.Data.Actor to MyMoviesFF.Web.Model.Actor.
        /// </summary>
        /// <param name="id">Actor's id.</param>
        /// <returns>Returns a Model.Actor.</returns>
        private Models.Actor GetActorModel(int id)
        {
            MyMoviesFF.Data.Actor oneactor = this.actingLogic.GetOneActor(id);
            return this.mapper.Map<MyMoviesFF.Data.Actor, Actor>(oneactor);
        }
    }
}

OENIK_PROG3_2020_2_WN1M1P/MyMoviesFF.Web/Views/Actors/ActorsDetails.cshtml
@model MyMoviesFF.Web.Models.Actor
@*@{
        @ViewData["Title"] = "ActorsDetails";
    }*@

<h2>Datasheet of one Actor </h2>

@Html.ActionLink("Back to the list", "Index")


<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(i => i.ActorId)</td>
        <td>@Html.DisplayFor(i => i.ActorId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.ActorName)</td>
        <td>@Html.DisplayFor(i => i.ActorName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Gender)</td>
        <td>@Html.DisplayFor(i => i.Gender)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Age)</td>
        <td>@Html.DisplayFor(i => i.Age)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Country)</td>
        <td>@Html.DisplayFor(i => i.Country)</td>
    </tr>
</table>

<h2>Movies in database</h2>
<table border="1">
    @foreach (var item in Model.MovieActors)
    {
        <tr>
            <td>
                @Html.DisplayFor(i => item.Movie.Title)
            </td>
        </tr>
    }
</table>

OENIK_PROG3_2020_2_WN1M1P/MyMoviesFF.Web/Views/Actors/ActorsEdit.cshtml
@model Actor

<h2>Actor Edit</h2>

@using (Html.BeginForm("Edit", "Actors")) //postként küldődik el
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(i => i.ActorId) // nem lehet szerkeszteni, rejtett adat

    @Html.Hidden("editAction", ViewData["editAction"].ToString()) // adatfelvitel, és modosítas, nem szép

    <div class="editor-label">@Html.LabelFor(i => i.ActorName)</div>
    <div class="editor-field">@Html.EditorFor(i => i.ActorName)</div>
    <br />
    <div class="editor-label">@Html.LabelFor(i => i.Gender)</div>
    <div class="editor-field"> Tick if male @Html.EditorFor(i => i.Gender)</div>
    <br />
    <div class="editor-label">@Html.LabelFor(i => i.Age)</div>
    <div class="editor-field">@Html.EditorFor(i => i.Age)</div>

    <div class="editor-label">@Html.LabelFor(i => i.Country)</div>
    <div class="editor-field">@Html.EditorFor(i => i.Country)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG3_2020_2_WN1M1P/MyMoviesFF.Web/Views/Actors/ActorsIndex.cshtml
@model MyMoviesFF.Web.Models.ActorListViewModel
@*@{
        @ViewData["Title"]= "ActorIndex";
    }*@

@*<h2>Actor index</h2>*@

<p style="color:red;">@TempData["editResult"]</p>

@await Html.PartialAsync("ActorsEdit", Model.EditedActor)

@await Html.PartialAsync("ActorsList", Model.ListOfActors)

OENIK_PROG3_2020_2_WN1M1P/MyMoviesFF.Web/Views/Actors/ActorsList.cshtml
@model IEnumerable<Actor>

<h2>Actor List</h2>

@if (Model.Count() == 0)
{
    <p>No Data</p>
}
else
{

    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(i => i.First().ActorName)</th>
            <th>@Html.DisplayNameFor(i => i.First().Gender)</th>
            <th>@Html.DisplayNameFor(i => i.First().Age)</th>
            <th>@Html.DisplayNameFor(i => i.First().Country)</th>

            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(i => item.ActorName)</td>
                <td>@Html.DisplayFor(i => item.Gender)</td>
                <td>@Html.DisplayFor(i => item.Age)</td>
                <td>@Html.DisplayFor(i => item.Country)</td>

                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ActorId })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ActorId })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ActorId })</td>
            </tr>
        }
    </table>
}